### ISSUE TITLE
test.fm on MaocOs High Sierra

### ISSUE THREAD

**Issue by ppkabore** [grafos-ml/frappe#30]
Hi,

I am trying to install test.fm on MacOs 10.13.6 but  got errors using
pip install https://github.com/grafos-ml/test.fm/archive/v1.0.4.tar.gz

Then I downloaded the source and compiled with
python compile.py build_ext 

Got same error:

Traceback (most recent call last):
  File "compile.py", line 14, in <module>
    pip.main(["install", "cython"])
AttributeError: 'module' object has no attribute 'main'

Thanks for your help.

**Comment by ChefWu551** [comment]
I have the same problem but in window...

**Comment by ppkabore** [comment]
I solved the problem by using python 2.x (I was using python 3.x) and ERPNext was not 100% stable with python 3.  But now, it is (depending on the version of ERPNext you're using).

Hope it helps.

**Comment by ChefWu551** [comment]
hello, thanks for answer, when i use version 2.7.18 it has the same problem, May u ask me the exactly version, I'll try

**Comment by ChefWu551** [comment]
![image](https://user-images.githubusercontent.com/33725817/80052260-da052380-854c-11ea-89a6-1af49ca05510.png)

**Comment by ChefWu551** [comment]
D:\迅雷下载>pip -V
pip 19.2.3 from c:\python27\lib\site-packages\pip (python 2.7)

D:\迅雷下载>python -V
Python 2.7.18

**Comment by ChefWu551** [comment]
version 2.7.13 will work  but it will have other problem
ERROR: Command errored out with exit status 1:
     command: 'c:\python36\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\lenovo\\AppData\\Local\\Temp\\pip-req-build-cvsi0be3\\setup.py'"'"'; __file__='"'"'C:\\Users\\lenovo\\AppData\\Local\\Temp\\pip-req-build-cvsi0be3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\lenovo\AppData\Local\Temp\pip-req-build-cvsi0be3\pip-egg-info'
         cwd: C:\Users\lenovo\AppData\Local\Temp\pip-req-build-cvsi0be3\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\lenovo\AppData\Local\Temp\pip-req-build-cvsi0be3\setup.py", line 11, in <module>
        from compile import ext_modules, build_ext
      File "C:\Users\lenovo\AppData\Local\Temp\pip-req-build-cvsi0be3\compile.py", line 59, in <module>
        raise EnvironmentError("Blas library is not detected in the system")
    OSError: Blas library is not detected in the system
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output
