### ISSUE TITLE
run "pip install https://github.com/grafos-ml/test.fm/archive/v1.0.4.tar.gz" fail

### ISSUE THREAD

**Issue by ChefWu551** [grafos-ml/frappe#32]
![image](https://user-images.githubusercontent.com/33725817/79964453-551ef900-84bd-11ea-9e99-d50104a2dc0f.png)

**Comment by ChefWu551** [comment]
pip install https://github.com/grafos-ml/test.fm/archive/v1.0.4.tar.gz
Collecting https://github.com/grafos-ml/test.fm/archive/v1.0.4.tar.gz
  Downloading https://github.com/grafos-ml/test.fm/archive/v1.0.4.tar.gz
     | 48.3 MB 168 kB/s
    ERROR: Command errored out with exit status 1:
     command: 'c:\python36\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\lenovo\\AppData\\Local\\Temp\\pip-req-build-3wk1eff9\\setup.py'"'"'; __file__='"'"'C:\\Users\\lenovo\\AppData\\Local\\Temp\\pip-req-build-3wk1eff9\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\lenovo\AppData\Local\Temp\pip-req-build-3wk1eff9\pip-egg-info'
         cwd: C:\Users\lenovo\AppData\Local\Temp\pip-req-build-3wk1eff9\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\lenovo\AppData\Local\Temp\pip-req-build-3wk1eff9\setup.py", line 11, in <module>
        from compile import ext_modules, build_ext
      File "C:\Users\lenovo\AppData\Local\Temp\pip-req-build-3wk1eff9\compile.py", line 59, in <module>
        raise EnvironmentError("Blas library is not detected in the system")
    OSError: Blas library is not detected in the system
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by shuairobin** [comment]
解决了吗？这个问题
